### ISSUE TITLE
Competencias genéricas

### ISSUE THREAD

**Issue by KarenCampos842** [KarenCampos842/Equipo-4#31]
Ir al archivo Descripción_del_proceso ubicado en la rama Primera-Entrega para leer especificaciones.
Fecha límite: Lunes 25 de septiembre.

**Comment by AsafCR** [comment]
Desarrollar la capacidad de comunicación del estudiante

Desarrollar la capacidad de comunicación como equipo 

Desarrollar la coordinación del equipo

Conocer a los compañeros de equipo
