### ISSUE TITLE
Competencias específicas

### ISSUE THREAD

**Issue by KarenCampos842** [KarenCampos842/Equipo-4#32]
Ir al archivo Descripción_del_proceso ubicado en la rama Primera-Entrega para leer especificaciones.
Fecha límite: Lunes 25 de septiembre.

**Comment by AsafCR** [comment]
Al realizar el proyecto en la plataforma GitHub se aprende a usar la misma de forma eficiente en equipo, lo cual ayudará a la vida profesional en el futuro

Al crear un proyecto con un "Cliente" ayuda a tener una idea de como sería el proceso de desarrollo de software y como la comunicación clara y concisa entre compañeros de equipo es importante para el desarrollo optimo de la visión del cliente

Al realizar un proyecto en equipo se busca aprender como trabajaría un equipo profesional de desarrollo de software

Se busca que el estudiante aprenda el proceso de creación del proyecto y sus pasos específicos, sus problemas más comunes y sus complicaciones frecuentes
